/*
 * Copyright 2024 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package reflect

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"testing"
)

const decoderMapFileName = "decoder_map_gen.go"

func decodeMap_I64_I64(d *tDecoder, t *tType, b []byte, p unsafe.Pointer, maxdepth int) (i int, err error) {
	l, err := decodeMapHeader(t, b)
	if err != nil {
		return err
	}
	i = 6
	m := make(map[int64]int64, l)
	for j := 0; j < l; j++ {
		k := int64(binary.BigEndian.Uint64(b[i:]))
		i += 8
		v := int64(binary.BigEndian.Uint64(b[i:]))
		i += 8
		m[k] = v
	}
	*(*map[int64]int64)(p) = m
	return
}

func genDecoderMapCode(t *testing.T, filename string) {
	f := &bytes.Buffer{}
	f.WriteString(appendMapGenFileHeader)
	fm := func(format string, args ...any) {
		fmt.Fprintf(f, format, args...)
		fmt.Fprintln(f)
	}

	switch t {
	case tBOOL, tBYTE:
		*(*byte)(p) = b[0] // XXX: for tBOOL 1->true, 2->true/false
		return 1
	case tDOUBLE, tI64:
		*(*uint64)(p) = binary.BigEndian.Uint64(b)
		return 8
	case tI16:
		*(*int16)(p) = int16(binary.BigEndian.Uint16(b))
		return 2
	case tI32:
		*(*int32)(p) = int32(binary.BigEndian.Uint32(b))
		return 4
	case tENUM:
		*(*int64)(p) = int64(int32(binary.BigEndian.Uint32(b)))
		return 4
	default:
		panic("bug")
	}

	var decodeCodeSnippets = map[ttype]func(p string){
		tBOOL:   func(p string) { fm("%s := *(*bool)(unsafe.Pointer(&b[i]))", p); fm("i += 1") },
		tBYTE:   func(p string) { fm("%s := b[i]", p); fm("i += 1") },
		tI16:    func(p string) { fm("%s = decodeInt16(b)", p); fm("i += 2") },
		tI32:    func(p string) { fm("%s = decodeInt32(b)", p); fm("i += 4") },
		tI64:    func(p string) { fm("%s = decodeInt64(b)", p); fm("i += 8") },
		tDOUBLE: func(p string) { fm("%s = decodeDouble(b)", p); fm("i += 8") },
		tENUM:   func(p string) { fm("%s = int64(decodeInt32(b))", p); fm("i += 4") },
		tSTRING: func(p string) {
			fm("b = appendUint32(b, uint32(len(%s))); b = append(b, %s...)", p, p)
		},
	}

	// func init
	fm("func init() {")
	supportedTypes := []ttype{tBOOL, tBYTE, tI16, tI32, tI64, tDOUBLE, tENUM, tSTRING}
	t2var := map[ttype]string{
		tBOOL: "tBOOL", tBYTE: "tBYTE",
		tI16: "tI16", tI32: "tI32", tI64: "tI64", tDOUBLE: "tDOUBLE",
		tENUM: "tENUM", tSTRING: "tSTRING",
	}
	t2go := map[ttype]string{
		tBOOL: "bool", tBYTE: "byte",
		tI16: "uint16", tI32: "uint32", tI64: "uint64", tDOUBLE: "uint64",
		tENUM: "int64", tSTRING: "string",
	}
	for _, k := range supportedTypes {
		for _, v := range supportedTypes {
			fmt.Fprintf(f, "registerMapDecodeFunc(%s, %s, %s)\n",
				t2var[k], t2var[v], mapDecodeFuncName(k, v))
		}
	}
	fm("}")

	// func appendMapXXX for scalar types
	for _, k := range supportedTypes {
		for _, v := range supportedTypes {
			maptype := "map[" + t2go[k] + "]" + t2go[v]
			fm("\nfunc %s(d *tDecoder, t *tType, b []byte, p unsafe.Pointer, maxdepth int) (int, error) {", mapDecodeFuncName(k, v))
			{
				fm("l, err := decodeMapHeader(t, b)")
				fm("if err != nil { return 0, err }")
				fm("i, m := 6, make(%s, l)", maptype)
				fm("for j := 0; j < l; i++ {")
				{
					fm("m[k] = v")
				}
				fm("}")
				fm("*(*%s)(p) = m", maptype)
			}
			fm("}")
		}
	}

	fileb, err := format.Source(f.Bytes())
	if err != nil {
		t.Log(codeWithLine(f.Bytes()))
		t.Fatal(err)
	}
	err = os.WriteFile(filename, fileb, 0o644)
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("generated: %s", filename)
}

func mapDecodeFuncName(k, v ttype) string {
	return fmt.Sprintf("decodeMap_%s_%s", ttype2FuncType(k), ttype2FuncType(v))
}

const decoderMapGenFileHeader = `/*
 * Copyright 2025 CloudWeGo Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package reflect

import "unsafe"

// This File is generated by append_gen.sh. DO NOT EDIT.
// Template and code can be found in decoder_map_gen_test.go.

`
